apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-config
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  # Redis ACL configuration matching Docker Compose setup
  # Format: user default off
  #         user <username> on ><password> allcommands allkeys
  users.acl: {{ printf "user default off\nuser %s on >%s allcommands allkeys" .Values.redis.auth.username .Values.redis.auth.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-auth
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.redis.auth.username | b64enc | quote }}
  password: {{ .Values.redis.auth.password | b64enc | quote }}
  # Redis connection string for applications
  redis-url: {{ printf "redis://%s:%s@%s:6379" .Values.redis.auth.username .Values.redis.auth.password (include "redis.fullname" .) | b64enc | quote }}
