networks:
  net:

services:
  server:
    image: ghcr.io/chroma-core/chroma
    volumes:
      - ${PWD}/chroma_data:/chroma/chroma
    ports:
      - "8800:8000"
    env_file:
     - ./.env
    environment:
     - CHROMA_SERVER_AUTHN_CREDENTIALS:${CHROMADB_ENCRYPTED_CREDS}
     - CHROMA_SERVER_AUTHN_PROVIDER:chromadb.auth.basic_authn.BasicAuthenticationServerProvider
     - ANONYMIZED_TELEMETRY:TRUE
     - IS_PERSISTENT:TRUE

    networks:
      - net
