replicaCount: 2

image:
  repository: newsies-api
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: newsies.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity: {}

# External service dependencies
redis:
  host: "newsies-redis-master"
  port: "6379"

chromadb:
  host: "newsies-chromadb"
  port: "8000"

postgresql:
  host: "newsies-postgresql"
  database: "newsies"
  username: "newsies"
