apiVersion: v2
name: newsies-analyzer
description: Newsies Content Analysis Service - Summarization and entity extraction
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - newsies
  - analysis
  - nlp
  - summarization
  - microservice
home: https://github.com/matthewapeters/newsies
sources:
  - https://github.com/matthewapeters/newsies
maintainers:
  - name: Matthew Peters
    email: matthew.peters@example.com
