"""newsies.llm.specs"""

_TRAINED_DATES_PATH = "./training_data/trained_dates.pkl"
_BASE_MODEL_NAME = "mistralai/Mistral-7B-v0.3"
BOOKS = "📚"
CLEAN = "🧹"
DISK = "💾"
FAIL = "❌"
INFO = "ℹ️"
NEWSIES = "📰"
OK = "✅"
PACKAGE = "📦"
SEARCH = "🔍"
TRAINING = "🧠"
WAIT = "⏳"
WARN = "⚠️"

CORPUS_PROMPT = (
    "for the next question, return the 'section', the 'headline', and the 'URI'\n"
)

TITLE_START = "[|TITLE START|]"
TITLE_END = "[|TITLE END|]"
ARTICLE_START = "[|ARTICLE START|]"
ARTICLE_END = "[|ARTICLE END|]"
ITEM_ID_START = "[|ITEM ID START|]"
ITEM_ID_END = "[|ITEM ID END|]"
SECTION_START = "[|SECTION START|]"
SECTION_END = "[|SECTION END|]"
PUBDATE_START = "[|PUBLISH DATE START|]"
PUBDATE_END = "[|PUBLISH DATE END|]"
AUTHOR_START = "[|AUTHOR START|]"
AUTHOR_END = "[|AUTHOR END|]"
SUMMARY_START = "[|SUMMARY START|]"
SUMMARY_END = "[|SUMMARY END|]"
