replicaCount: 1

image:
  repository: ghcr.io/chroma-core/chroma
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chromadb.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# ChromaDB specific configuration
chromadb:
  # Authentication settings
  auth:
    enabled: true
    username: "user1"
    password: "password123"
  
  # ChromaDB settings matching Docker Compose
  allowReset: "TRUE"
  anonymizedTelemetry: "TRUE"
  isPersistent: "TRUE"
  
  # Persistence configuration - using existing volume mount points
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 8Gi
    # Mount path matching Docker Compose: /chroma/chroma
    mountPath: "/chroma/chroma"
    # Host path for local development (matching docker-compose volume)
    hostPath: "/home/mpeters/Projects/newsies/docker/chroma_data"
