#! /bin/bash
export CHROMADB_HOST=localhost
export CHROMADB_PORT=8800
export CHROMADB_USER="user1"
chromadb_password="password123"
export CHROMADB_CREDS="${CHROMADB_USER}:${chromadb_password}"
export TOKENIZERS_PARALLELISM=true

flag=$1


case $flag in
    start)
        echo "Starting Chroma"
	export CHROMADB_ENCRYPTED_CREDS=`docker run --rm --entrypoint htpasswd httpd:2 -Bbn $CHROMADB_USER $chromadb_password`
	echo $CHROMADB_CREDS
	echo $CHROMADB_ENCRYPTED_CREDS
        pushd docker &>/dev/null
        docker compose up -d
        popd &>/dev/null
        ;;
    stop)
        echo "Stopping Chroma"
        pushd docker &>/dev/null
        docker compose down
        popd &>/dev/null
        ;;
    chroma-stats)
        echo "Chroma Stats"
        echo "-------------"
        echo "CTRL-C To Exit"
        echo
        for i in {1..3}; do
            echo -n "."
            sleep 1
        done
        pushd docker &>/dev/null
        docker compose stats
        popd &>/dev/null
        ;;
    chroma-logs)
        echo "Chroma Logs"
        echo "-------------"
        echo "CTRL-C To Exit"
        echo
        for i in {1..3}; do
            echo -n "."
            sleep 1
        done
        pushd docker &>/dev/null
        docker compose logs -f
        popd &>/dev/null
        ;;

    *)
        echo "Usage: newsies [start|stop|chroma-stats|chroma-logs]"
        ;;
esac

