#! /bin/bash
export CHROMADB_HOST=localhost
export CHROMADB_PORT=8800
export CHROMADB_USER="user1"
chromadb_password="password123"
export REDIS_USER="user2"
redis_password="redisCache123#"
export CHROMADB_CREDS="${CHROMADB_USER}:${chromadb_password}"
export REDIS_CREDS="${REDIS_USER}:${redis_password}"
export TOKENIZERS_PARALLELISM=true

flag=$1

logo(){
    echo "+----------------------------------------+
|                                        |
|             .......                    |
|            .~~~~~~~~..                 |
|           .~.~~~~~.......              |
|           .~~~~... ..   .              |
|           .~~~...~:~~~.                |
|           .~. .~+:+:~~.                |
|              ..:::+~~.                 |
|           ~:::~::~:~~~~~~~..           |
|         .=o=+==+~:+++++=====+:.        |
|        .o==++=+~~=====+===+=+=+.       |
|       ~o===+++~.+====++==++++++++~     |
|      ~o===+:~~.:o===++::+~::=++++=:    |
|      =o==+~~~~+===+:+++~::..::+==+:    |
|     .=oo=+:::::::~~~::+.~~  .+==++~    |
|      :====+:=o+.......  . .~==++:.     |
|      :o===++o=+~ ..... .~:+=+:~+.      |
|     .=oo::=+=o+~ .... .:+++:.          |
|     +ooo==+++++~ .... ..::~            |
|    :oo==oo++:::~  ....                 |
|    =oo==o=++::++  ......               |
|    .=ooooo=+:+:=. ... ...              |
|      .~::+++++++  .... ...             |
|        ~........ .....  .              |
|        ........ ......                 |
|        ...... .  ...  . .              |
|         ~... .. ..........             |
|         ~.....  ..........             |
|         ........  ..... .              |
|           ..... . .~.....              |
|            .~...~   .....              |
|             ~~...    ....              |
|             ~~~..    .~...             |
|            .~:~~.    .:..~             |
|          .~:~~~..    .::~~.            |
|        .~:::~...     .::~:~.           |
|       .::~~~..       .::::~~.          |
|                       ....             |
+----------------------------------------+"
}


case $flag in
    start)
        echo "Starting ChromaDB and Redis"
        export CHROMADB_ENCRYPTED_CREDS=`docker run --rm --entrypoint htpasswd httpd:2 -Bbn $CHROMADB_USER $chromadb_password`
        echo "
user default off
user ${REDIS_USER} on >${redis_password} allcommands allkeys" > ./docker/redis-users.acl
        echo $CHROMADB_CREDS
        echo $REDIS_CREDS
        echo $CHROMADB_ENCRYPTED_CREDS
        echo "
# CHROMA DB SETTINGS
CHROMA_SERVER_AUTHN_CREDENTIALS='${CHROMADB_ENCRYPTED_CREDS}'
        ">./docker/.chroma_env
        pushd docker &>/dev/null
        docker compose up -d --remove-orphans
        popd &>/dev/null
        ;;
    stop)
        echo "Stopping ChromaDB and Redis"
        pushd docker &>/dev/null
        docker compose down
        popd &>/dev/null
        ;;
    chroma-stats)
        echo "Chroma Stats"
        echo "-------------"
        echo "CTRL-C To Exit"
        echo
        for i in {1..3}; do
            echo -n "."
            sleep 1
        done
        pushd docker &>/dev/null
        docker compose stats
        popd &>/dev/null
        ;;
    get-news)
        python -m newsies.main get-news
        ;;
    analyze)

        export NLTK_DATA="~/nltk_data"
        export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
        python -m newsies.main analyze
        ;;
    cli)
        python -m newsies.main cli
        ;;
    serve)
        nohup uvicorn newsies.api.app:app > newsies.log 2>newsies_err.log 1>newsies.log &
        serve_pid=$!
        echo $serve_pid>.newsies.pid
        disown $serve_pid
        tail -f ./newsies*.log &
        tail_pid=$!
        disown $tail_pid
        echo "Tailing newsies.log -- ctrl-c to end log tailing (server will continue)"
        wait $tail_pid
        ;;
    kill)
        PID=`cat .newsies.pid`
        echo "terminating newsies server ($PID)"
        kill $PID
        ;;
    api)
        xdg-open http://localhost:8000/docs
        ;;
    chroma-logs)
        echo "Chroma Logs"
        echo "-------------"
        echo "CTRL-C To Exit"
        echo
        for i in {1..3}; do
            echo -n "."
            sleep 1
        done
        pushd docker &>/dev/null
        docker compose logs -f
        popd &>/dev/null
        ;;

    *)
        logo
        echo
        echo Newsies Usage
        echo
        echo "Usage: newsies [routine]"
        echo "CLI Commands"
        echo -e "\tget-news"
        echo -e "\tanalyze"
        echo -e "\tcli"
        echo -e "\tstart"
        echo -e "\tstop"
        echo -e "\tchroma-stats"
        echo -e "\tchroma-logs"
        echo "--------------"
        echo "API Server"
        echo -e "\tserve"
        echo -e "\tkill"
        echo -e "\tapi"
        ;;
esac

