apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chromadb.fullname" . }}
  labels:
    {{- include "chromadb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chromadb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "chromadb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chromadb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: CHROMA_SERVER_AUTHN_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: {{ include "chromadb.fullname" . }}-secret
                  key: auth-credentials
            - name: CHROMA_SERVER_AUTHN_PROVIDER
              value: "chromadb.auth.basic_authn.BasicAuthenticationServerProvider"
            - name: ANONYMIZED_TELEMETRY
              value: "TRUE"
            - name: IS_PERSISTENT
              value: "TRUE"
            - name: ALLOW_RESET
              value: "{{ .Values.chromadb.allowReset | default "TRUE" }}"
            - name: PERSIST_DIRECTORY
              value: "/chroma/chroma"
          livenessProbe:
            httpGet:
              path: /api/v1/heartbeat
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/heartbeat
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: chroma-data
              mountPath: /chroma/chroma
      volumes:
        - name: chroma-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "chromadb.fullname" .) }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
